### ISSUE TITLE
Not working on Windows and cannot convert all files at once (workaround)

### ISSUE THREAD

**Issue by abbydiode** [WolvenKit/wwise-audio-tools#12]
Running `wwtools` in the command line on Windows does nothing. I tried it on WSL and got an output, however trying to make it convert all files at once also does not work on WSL.

I've written this quick script as a workaround for anyone else who is struggling with this issue. It just takes all `.wem` files in the current directory and passes them to `wwtools` individually, which for some reason does work.

```bash
#!/bin/bash
echo Converting all .wem files to .ogg
shopt -s nullglob
for i in *.wem; do
    ./wwtools wem $i
done
echo Done
```

**Comment by ADawesomeguy** [comment]
Nice, thank you! I'll take a look at this and see if I can fix it. I'm not sure exactly what must be going wrong since theoretically it's just looping through all the files provided by `std::filesystem` meaning there should be no cross platform problem but I'll do some testing and see if I can fix it.
